
skillMetadata:
  sections:
    - name: Options
      fields:
        - name: bulb_ip
          type: text
          label: Your Bulbs IP Address
          value: ""
          placeholder: demo prompt in the input box
